name: appsflyer_sdk
description: A Flutter plugin for AppsFlyer SDK. Supports iOS and Android.
version: 1.0.8
authors:
  - Shahar Cohen <shahar.cohen@appsflyer.com>
  - Maxim Shoustin <maxim@appsflyer.com>
  - Benjamin Winestein <benjamin@appsflyer.com>
homepage: https://github.com/AppsFlyerSDK/flutter_appsflyer_sdk

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: 3.0.0

flutter:
  plugin:
    androidPackage: com.appsflyer.appsflyersdk
    pluginClass: AppsflyerSdkPlugin
