name: appsflyer_sdk
description: A Flutter plugin for AppsFlyer SDK. Supports iOS and Android.
version: 6.4.0+1

homepage: https://github.com/AppsFlyerSDK/flutter_appsflyer_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  mockito: 5.0.11
  effective_dart: ^1.3.0


flutter:
  plugin:
    platforms:
      android:
        package: com.appsflyer.appsflyersdk
        pluginClass: AppsflyerSdkPlugin
      ios:
        pluginClass: AppsflyerSdkPlugin
        package: com.appsflyer.appsflyersdk
