name: appsflyer_sdk
description: A Flutter plugin for AppsFlyer SDK. Supports iOS and Android.
version: 6.17.6

homepage: https://github.com/AppsFlyerSDK/flutter_appsflyer_sdk

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
  mockito: ^5.4.4
  effective_dart: ^1.3.0
  build_runner: ^2.3.0
  json_serializable: ^6.5.4


flutter:
  plugin:
    platforms:
      android:
        package: com.appsflyer.appsflyersdk
        pluginClass: AppsflyerSdkPlugin
      ios:
        pluginClass: AppsflyerSdkPlugin
        package: com.appsflyer.appsflyersdk
